attacking_attributes = [
    "goals_per90",
    "goals_per_shot_on_target_per90",
    "goals_per_shot_per90",
    "npxg_net_per90",
    "npxg_per90",
    "npxg_per_shot_per90",
    "offsides_per90",
    "pens_att_per90",
    "pens_made_per90",
    "shots_free_kicks_per90",
    "shots_on_target_pct",
    "shots_on_target_per90",
    "shots_total_per90",
    "xg_net_per90",
    "xg_per90",
]
defensive_attributes = [
    "aerials_lost_per90",
    "aerials_won_pct",
    "aerials_won_per90",
    "ball_recoveries_per90",
    "blocked_passes_per90",
    "blocked_shots_per90",
    "blocked_shots_saves_per90",
    "blocks_per90",
    "cards_yellow_red_per90",
    "clearances_per90",
    "dribble_tackles_pct",
    "dribble_tackles_per90",
    "dribbled_past_per90",
    "dribbles_vs_per90",
    "errors_per90",
    "fouls_per90",
    "interceptions_per90",
    "own_goals_per90",
    "pens_conceded_per90",
    "pressure_regain_pct",
    "pressure_regains_per90",
    "pressures_att_3rd_per90",
    "pressures_def_3rd_per90",
    "pressures_mid_3rd_per90",
    "pressures_per90",
    "tackles_att_3rd_per90",
    "tackles_def_3rd_per90",
    "tackles_mid_3rd_per90",
    "tackles_per90",
    "tackles_won_per90",
]
dribbling_attributes = [
    "carries_per90",
    "carry_distance_per90",
    "carry_progressive_distance_per90",
    "dispossessed_per90",
    "dribbles_completed_pct",
    "dribbles_completed_per90",
    "dribbles_per90",
    "fouled_per90",
    "miscontrols_per90",
    "nutmegs_per90",
    "pens_won_per90",
    "players_dribbled_past_per90",
    "touches_att_3rd_per90",
    "touches_att_pen_area_per90",
    "touches_def_3rd_per90",
    "touches_def_pen_area_per90",
    "touches_live_ball_per90",
    "touches_mid_3rd_per90",
    "touches_per90",
]
passing_attributes = [
    "assisted_shots_per90",
    "assists_per90",
    "corner_kicks_in_per90",
    "corner_kicks_out_per90",
    "corner_kicks_per90",
    "corner_kicks_straight_per90",
    "crosses_into_penalty_area_per90",
    "crosses_per90",
    "gca_dribbles_per90",
    "gca_fouled_per90",
    "gca_og_for_per90",
    "gca_passes_dead_per90",
    "gca_passes_live_per90",
    "gca_per90",
    "gca_shots_per90",
    "pass_targets_per90",
    "passes_blocked_per90",
    "passes_completed_long_per90",
    "passes_completed_medium_per90",
    "passes_completed_per90",
    "passes_completed_short_per90",
    "passes_dead_per90",
    "passes_free_kicks_per90",
    "passes_ground_per90",
    "passes_head_per90",
    "passes_high_per90",
    "passes_intercepted_per90",
    "passes_into_final_third_per90",
    "passes_into_penalty_area_per90",
    "passes_left_foot_per90",
    "passes_live_per90",
    "passes_long_per90",
    "passes_low_per90",
    "passes_medium_per90",
    "passes_offsides_per90",
    "passes_oob_per90",
    "passes_other_body_per90",
    "passes_pct",
    "passes_pct_long",
    "passes_pct_medium",
    "passes_pct_short",
    "passes_per90",
    "passes_pressure_per90",
    "passes_progressive_distance_per90",
    "passes_received_pct",
    "passes_received_per90",
    "passes_right_foot_per90",
    "passes_short_per90",
    "passes_switches_per90",
    "passes_total_distance_per90",
    "progressive_passes_per90",
    "sca_dribbles_per90",
    "sca_fouled_per90",
    "sca_passes_dead_per90",
    "sca_passes_live_per90",
    "sca_per90",
    "sca_shots_per90",
    "through_balls_per90",
    "throw_ins_per90",
    "xa_net_per90",
    "xa_per90",
]
discipline_attributes = ["cards_red_per90", "cards_yellow_per90"]

english_teams = [
    "Arsenal",
    "Aston Villa",
    "Bournemouth",
    "Brighton",
    "Burnley",
    "Chelsea",
    "Crystal Palace",
    "Everton",
    "Leicester City",
    "Liverpool",
    "Manchester City",
    "Manchester Utd",
    "Newcastle Utd",
    "Norwich City",
    "Sheffield Utd",
    "Southampton",
    "Tottenham",
    "Watford",
    "West Ham",
    "Wolves",
]
spanish_teams = [
    "Alavés",
    "Athletic Club",
    "Atlético Madrid",
    "Barcelona",
    "Betis",
    "Celta Vigo",
    "Eibar",
    "Espanyol",
    "Getafe",
    "Granada",
    "Leganés",
    "Levante",
    "Mallorca",
    "Osasuna",
    "Real Madrid",
    "Real Sociedad",
    "Sevilla",
    "Valencia",
    "Valladolid",
    "Villarreal",
]
german_teams = [
    "Augsburg",
    "Bayern Munich",
    "Dortmund",
    "Düsseldorf",
    "Eint Frankfurt",
    "Freiburg",
    "Hertha BSC",
    "Hoffenheim",
    "Köln",
    "Leverkusen",
    "M'gladbach",
    "Mainz 05",
    "Paderborn 07",
    "RB Leipzig",
    "Schalke 04",
    "Union Berlin",
    "Werder Bremen",
    "Wolfsburg",
]
italian_teams = [
    "Atalanta",
    "Bologna",
    "Brescia",
    "Cagliari",
    "Fiorentina",
    "Genoa",
    "Hellas Verona",
    "Inter",
    "Juventus",
    "Lazio",
    "Lecce",
    "Milan",
    "Napoli",
    "Parma",
    "Roma",
    "SPAL",
    "Sampdoria",
    "Sassuolo",
    "Torino",
    "Udinese",
]
french_teams = [
    "Amiens",
    "Angers",
    "Bordeaux",
    "Brest",
    "Dijon",
    "Lille",
    "Lyon",
    "Marseille",
    "Metz",
    "Monaco",
    "Montpellier",
    "Nantes",
    "Nice",
    "Nîmes",
    "Paris S-G",
    "Reims",
    "Rennes",
    "Saint-Étienne",
    "Strasbourg",
    "Toulouse",
]
