ATTRIBUTES = {
    "Attacking": [
        "Goals",
        "Shots",
        "Shots on Target",
        "xG",
        "npxG",
        "SCA",
        "GCA",
        "Assists",
        "Key Passes",
        "Passes into Final Third",
        "Passes into Penalty Area",
        "Crosses into Penalty Area",
    ],
    "Defending": [
        "Tackles Attempted",
        "Tackles Won",
        "Tackles in Defensive 3rd",
        "Tackles in Middle 3rd",
        "Tackles in Attacking 3rd",
        "Dribblers tackled",
        "Dribbles contested",
        "Number of times dribbled past",
        "Pressures",
        "Successful Pressues",
        "Pressures in Defensive 3rd",
        "Pressures in Middle 3rd",
        "Pressures in Attacking 3rd",
        "Blocks",
        "Shots Blocked",
        "Shots on Target Blocked",
        "Passess Blocked",
        "Interceptions",
        "Clearances",
        "Errors",
    ],
    "Dribbling": [
        "Touches",
        "Touches in Defensive Penalty Area",
        "Touches in Defensive 3rd",
        "Touches in Middle 3rd",
        "Touches in Attacking 3rd",
        "Touches in Attacking Penalty Area",
        "Successful Dribbles",
        "Attempted Dribbles",
        "Nutmegs",
        "Carries",
        "Progressive Distance via Carries",
        "Carries into Final Third",
        "Carries into Penalty Area",
        "Dispossessions",
    ],
    "Miscellaneous": [
        "Pass Targets",
        "Passes Received",
        "Miscontrols",
        "Yellow Cards",
        "Red Cards",
        "Fouls",
        "Number of times fouled",
        "Offsides",
        "Crosses",
        "Number of Penalty Kicks Won",
        "Number of Penalty Kicks Conceded",
        "Own Goals",
        "Recoveries",
        "Aerial Duels Won",
        "Aerial Duels Lost",
    ],
}

POSITIONS_DELIMITER = ","

POSITIONS = ["DF", "MF", "FW"]

SEASONS = ["2022-2023", "2021-2022", "2020-2021", "2019-2020", "2018-2019"]

COLUMNS_RENAMING_MAP = {
    "Team Country_": "Team Country",
    "Team Name_": "Team Name",
    "Player": "Player Name",
    "Nation": "Nationality",
    "Age": "Age",
    "Standard_Gls": "Goals",
    "Standard_Sh": "Shots",
    "Standard_SoT": "Shots on Target",
    "Expected_xG": "xG",
    "Expected_npxG": "npxG",
    "SCA_SCA": "SCA",
    "GCA_GCA": "GCA",
    "Tackles_Tkl": "Tackles Attempted",
    "Tackles_TklW": "Tackles Won",
    "Tackles_Def 3rd": "Tackles in Defensive 3rd",
    "Tackles_Mid 3rd": "Tackles in Middle 3rd",
    "Tackles_Att 3rd": "Tackles in Attacking 3rd",
    "Vs Dribbles_Tkl": "Dribblers tackled",
    "Vs Dribbles_Att": "Dribbles contested",
    "Vs Dribbles_Past": "Number of times dribbled past",
    "Pressures_Press": "Pressures",
    "Pressures_Succ": "Successful Pressues",
    "Pressures_Def 3rd": "Pressures in Defensive 3rd",
    "Pressures_Mid 3rd": "Pressures in Middle 3rd",
    "Pressures_Att 3rd": "Pressures in Attacking 3rd",
    "Blocks_Blocks": "Blocks",
    "Blocks_Sh": "Shots Blocked",
    "Blocks_ShSv": "Shots on Target Blocked",
    "Blocks_Pass": "Passess Blocked",
    "Int": "Interceptions",
    "Clr": "Clearances",
    "Err": "Errors",
    "Touches_Touches": "Touches",
    "Touches_Def Pen": "Touches in Defensive Penalty Area",
    "Touches_Def 3rd": "Touches in Defensive 3rd",
    "Touches_Mid 3rd": "Touches in Middle 3rd",
    "Touches_Att 3rd": "Touches in Attacking 3rd",
    "Touches_Att Pen": "Touches in Attacking Penalty Area",
    "Dribbles_Succ": "Successful Dribbles",
    "Dribbles_Att": "Attempted Dribbles",
    "Dribbles_Megs": "Nutmegs",
    "Carries_Carries": "Carries",
    "Carries_PrgDist": "Progressive Distance via Carries",
    "Receiving_Targ": "Pass Targets",
    "Receiving_Rec": "Passes Received",
    "Performance_CrdY": "Yellow Cards",
    "Performance_CrdR": "Red Cards",
    "Performance_Fls": "Fouls",
    "Performance_Fld": "Number of times fouled",
    "Performance_Off": "Offsides",
    "Performance_Crs": "Crosses",
    "Performance_PKwon": "Number of Penalty Kicks Won",
    "Performance_PKcon": "Number of Penalty Kicks Conceded",
    "Performance_OG": "Own Goals",
    "Performance_Recov": "Recoveries",
    "Aerial Duels_Won": "Aerial Duels Won",
    "Aerial Duels_Lost": "Aerial Duels Lost",
    "Playing Time_Min": "Minutes",
    "Ast": "Assists",
    "KP": "Key Passes",
    "1/3": "Passes into Final Third",
    "PPA": "Passes into Penalty Area",
    "CrsPA": "Crosses into Penalty Area",
    "Carries_1/3": "Carries into Final Third",
    "Carries_CPA": "Carries into Penalty Area",
    "Carries_Mis": "Miscontrols",
    "Carries_Dis": "Dispossessions",
}


UNWANTED_COLUMNS = [
    "Standard_G/Sh",
    "Standard_SoT%",
    "Standard_G/Sh",
    "Standard_G/SoT",
    "Standard_Dist",
    "Standard_FK",
    "Standard_PK",
    "Standard_PKatt",
    "Expected_npxG/Sh",
    "Expected_G-xG",
    "Expected_G-xG",
    "Expected_np:G-xG",
    "SCA Types_PassLive",
    "SCA Types_PassDead",
    "SCA Types_Drib",
    "SCA Types_Sh",
    "SCA Types_Fld",
    "SCA Types_Def",
    "GCA Types_PassLive",
    "GCA Types_PassDead",
    "GCA Types_Drib",
    "GCA Types_Sh",
    "GCA Types_Fld",
    "GCA Types_Def",
    "Vs Dribbles_Tkl%",
    "Pressures_%",
    "Tkl+Int",
    "Dribbles_Succ%",
    "Dribbles_#Pl",
    "Receiving_Rec%",
    "Aerial Duels_Won%",
    "Playing Time_MP",
    "Playing Time_Mn/MP",
    "Playing Time_Min%",
    "Starts_Starts",
    "Starts_Mn/Start",
    "Starts_Compl",
    "Subs_Subs",
    "Subs_Mn/Sub",
    "Subs_unSub",
    "Team Success_PPM",
    "Team Success_onG",
    "Team Success_onGA",
    "Team Success_+/-",
    "Team Success_On-Off",
    "Team Success (xG)_onxG",
    "Team Success (xG)_onxGA",
    "Team Success (xG)_xG+/-",
    "Team Success (xG)_On-Off",
    "Unnamed: 0",
    "Touches_Live",
    "Carries_TotDist",
    "Performance_2CrdY",
    "Performance_Int",
    "Performance_TklW",
    "Total_Cmp",
    "Total_Att",
    "Total_Cmp%",
    "Total_TotDist",
    "Total_PrgDist",
    "Short_Cmp",
    "Short_Att",
    "Short_Cmp%",
    "Medium_Cmp",
    "Medium_Att",
    "Medium_Cmp%",
    "Long_Cmp",
    "Long_Att",
    "Long_Cmp%",
    "A-xA",
    "Prog",
    "Carries_Prog",
]

BIG_5_TABLE_URL = "https://fbref.com/en/comps/Big5/{}/{}-Big-5-European-Leagues-Stats"
TEAM_URL = "https://fbref.com/en/squads/{}/{}/{}-Stats"

FILENAME_TEMPLATE = "./Data/Top5Leagues_{}.csv"

ATTRIBUTES_NOT_TO_BE_SCALED = [
    "Player Name",
    "Nationality",
    "Team Name",
    "Position 1",
    "Position 2",
    "Position 3",
    "Age",
    "Team Country",
]
