ATTRIBUTES = {
    "Attacking": [
        "Goals",
        "Shots",
        "Shots on Target",
        "xG",
        "npxG",
        "SCA",
        "GCA",
        "Assists",
        "Key Passes",
        "Passes into Final Third",
        "Passes into Penalty Area",
        "Crosses into Penalty Area",
    ],
    "Defending": [
        "Tackles Attempted",
        "Tackles Won",
        "Tackles in Defensive 3rd",
        "Tackles in Middle 3rd",
        "Tackles in Attacking 3rd",
        "Dribblers tackled",
        "Dribbles contested",
        "Number of times dribbled past",
        "Pressures",
        "Successful Pressues",
        "Pressures in Defensive 3rd",
        "Pressures in Middle 3rd",
        "Pressures in Attacking 3rd",
        "Blocks",
        "Shots Blocked",
        "Shots on Target Blocked",
        "Passess Blocked",
        "Interceptions",
        "Clearances",
        "Errors",
    ],
    "Dribbling": [
        "Touches",
        "Touches in Defensive Penalty Area",
        "Touches in Defensive 3rd",
        "Touches in Middle 3rd",
        "Touches in Attacking 3rd",
        "Touches in Attacking Penalty Area",
        "Successful Dribbles",
        "Attempted Dribbles",
        "Nutmegs",
        "Carries",
        "Progressive Distance via Carries",
        "Carries into Final Third",
        "Carries into Penalty Area",
        "Dispossessions",
    ],
    "Miscellaneous": [
        "Pass Targets",
        "Passes Received",
        "Miscontrols",
        "Yellow Cards",
        "Red Cards",
        "Fouls",
        "Number of times fouled",
        "Offsides",
        "Crosses",
        "Number of Penalty Kicks Won",
        "Number of Penalty Kicks Conceded",
        "Own Goals",
        "Recoveries",
        "Aerial Duels Won",
        "Aerial Duels Lost",
    ],
}

POSITIONS_DELIMITER = ","
